apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xeks.aws.moonorb.com
spec:
  scope: Cluster
  group: aws.moonorb.com
  names:
    kind: XEKS
    plural: xeks
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                crossplane:
                  type: object
                  description: Crossplane-specific configuration
                  properties:
                    compositionRef:
                      type: object
                      properties:
                        name:
                          type: string
                    compositionRevisionRef:
                      type: object
                      properties:
                        name:
                          type: string
                    resourceRefs:
                      type: array
                      items:
                        type: object
                        properties:
                          apiVersion:
                            type: string
                          kind:
                            type: string
                          name:
                            type: string
                parameters:
                  type: object
                  description: EKS configuration parameters.
                  properties:
                    id:
                      type: string
                      description: ID of this Cluster that other objects will use to refer to it.
                    region:
                      type: string
                      description: Region is the region you'd like your resource to be created in.
                    iam:
                      type: object
                      description: IAM configuration to connect as ClusterAdmin.
                      properties:
                        roleArn:
                          description: The IAM Role ARN to connect as ClusterAdmin.
                          type: string
                          default: roleArn
                        userArn:
                          description: The IAM User ARN to connect as ClusterAdmin.
                          type: string
                          default: userArn
                        autoscalerArn:
                          description: The AutoScaler Role ARN to connect as ClusterAdmin.
                          type: string
                          default: autoscalerArn
                    subnetIds:
                      description: EKS Cluster Subnet Id references
                      items:
                        type: string
                      type: array
                      default: []
                    publicAccessCidrs:
                      description: CIDRs that allow K8s API-Should be set to VPC CID of the MGMT cluster
                      items:
                        type: string
                      type: array
                      default: []   
                    deletionPolicy:
                      description: Delete the external resources when the Claim/XR is deleted. Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                    endpointPrivateAccess:
                      description: Allow K8S API server access from private subnets
                      type: boolean
                      default: true
                    endpointPublicAccess:
                      description: Allow K8S API server access from public
                      type: boolean
                      default: false
                    additionalCidrIpv4:
                      description: Additional CIDRs to allow EKS API Server access
                      type: array
                      items:
                        type: string
                      default: []
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources
                      type: string
                      default: default
                    version:
                      description: Kubernetes version
                      type: string
                      pattern: "^1\\.(2[6-9]|3[0-5])$"
                    authenticationMode:
                      description: EKS authentication mode. Defaults to CONFIG_MAP
                      type: string
                      enum:
                        - API
                        - API_AND_CONFIG_MAP
                      default: API_AND_CONFIG_MAP
                    tags:
                      additionalProperties:
                        type: string
                      type: object
                    enableSecondaryNetworking:
                      type: boolean
                      description: |
                        Enable secondary CIDR networking for pods. When enabled:
                        - Requires exactly 3 subnet IDs in customNetworkingSubnetIds
                        - Creates ENIConfig resources for custom pod networking
                        - Configures VPC-CNI with AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG=true
                        - Pods will use secondary CIDR subnets instead of node subnets
                      default: false
                    customNetworkingSubnetIds:
                      type: array
                      description: |
                        Subnet IDs for secondary CIDR networking. When enableSecondaryNetworking is true:
                        - Requires exactly 3 subnet IDs (one per availability zone)
                        - Creates ENIConfig resources for custom pod networking
                        - Subnets must be in secondary CIDR blocks
                      items:
                        type: string
                      default: []
                    nodes:
                      type: object
                      description: EKS node configuration parameters.
                      properties:
                        count:
                          type: integer
                          description: Desired node count, from 1 to 100.
                        instanceType:
                          type: string
                          description: instance types associated with the Node Group.
                          default: t3.small
                        diskSize:
                          type: integer
                          description: Disk Size for each node. Default 20G if not defined
                      required:
                        - count
                        - instanceType
                    addons:
                      type: object
                      properties:
                        vpc-cni:
                          description: vpc-cni addon version
                          type: string
                          pattern: ^v\d+\.\d+\.\d+-eksbuild\.1$                        
                  required:
                    - id
                    - region
                    - subnetIds
                    - providerConfigName
                    - version
              required:
                - parameters
            status:
              description: A Status represents the observed state
              properties:
                eks:
                  description: Freeform field containing status information for eks
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              type: object

